### PR TITLE
fix(gamm): setting correct module account to gamm

### LINKED ISSUE #61: setting module account to gamm incorrectly
when creating a module account for the pool we didn't call authKeeper.NewAccount() which set the correct account number to the pool account and increment the `global account number`. This will lead to the pool account having 0 account number and overwrite the (account number -> account) entry that has 0 as the account number, as well as making the `global account number` incorrect.

### PR DESCRIPTION
**Pull request by hoangdv2429**
Closes: #61

Setting correct module account to gamm. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by mtsitrin** [comment]
@hoangdv2429 pls clarify
this PR reverts my previous PR.

the `osmoutils.CreateModuleAccount` creates malformed `ModuleAccount` which can't. be exported

why `k.accountKeeper.SetModuleAccount` is not good enough?

**Comment by hoangdv2429** [comment]
> @hoangdv2429 pls clarify this PR reverts my previous PR.
> 
> the `osmoutils.CreateModuleAccount` creates malformed `ModuleAccount` which can't. be exported
> 
> why `k.accountKeeper.SetModuleAccount` is not good enough?

In your previous code we didn't call authKeeper.NewAccount(). It's well explained in the issue I think

File: x/poolmanager/keeper/create_pool.go [hunk 1]
```diff
@@ -60,15 +60,24 @@ func (k Keeper) CreatePool(ctx sdk.Context, msg types.CreatePoolMsg) (uint64, er
...
 	}
-	k.accountKeeper.SetModuleAccount(ctx, authtypes.NewEmptyModuleAccount(poolName))
+	// Create a new module account for the pool.
+	moduleAccount := authtypes.NewEmptyModuleAccount(poolName)
+	moduleAccountI, ok := (k.accountKeeper.NewAccount(ctx, moduleAccount)).(authtypes.ModuleAccountI) // set the account number
+	if !ok {
+		return 0, fmt.Errorf("cannot create module account %s, "+
+			"failed to set account number", poolAddr)
+	}
+	k.accountKeeper.SetModuleAccount(ctx, moduleAccountI)
```
Comment (zale144) [inline x/poolmanager/keeper/create_pool.go:70]:
```suggestion
	moduleAccount := authtypes.NewEmptyModuleAccount(poolName)
	_ = moduleAccount.SetAccountNumber(k.accountKeeper.GetNextAccountNumber(ctx))
	k.accountKeeper.SetAccount(ctx, moduleAccount)
```

File: x/poolmanager/types/expected_keepers.go [hunk 2]
```diff
@@ -9,7 +9,9 @@ import (
 // AccountI defines the account contract that must be fulfilled when
 // creating a x/gamm keeper.
 type AccountI interface {
+	NewAccount(sdk.Context, authtypes.AccountI) authtypes.AccountI
 	GetAccount(ctx sdk.Context, addr sdk.AccAddress) authtypes.AccountI
+	SetAccount(ctx sdk.Context, acc authtypes.AccountI)
```
Comment (zale144) [inline x/poolmanager/types/expected_keepers.go:14]: I don't think `NewAccount` and `SetAccount` are used anywhere

**Review by zale144 — CHANGES_REQUESTED** [review]

File: x/poolmanager/keeper/create_pool.go (hunk 1 above)
Comment (hoangdv2429) [reply x/poolmanager/keeper/create_pool.go:70]: @zale144 we need to set it that way to prevent it from having 0 as account number. I discussed it with @mtsitrin

Comment (zale144) [reply x/poolmanager/keeper/create_pool.go:70]: @hoangdv2429 just saw your reply. Got it, I updated my comment with another way it can be done

File: x/poolmanager/types/expected_keepers.go (hunk 2 above)
Comment (zale144) [inline x/poolmanager/types/expected_keepers.go:14]:
```suggestion
	GetNextAccountNumber(ctx sdk.Context) uint64
	GetAccount(ctx sdk.Context, addr sdk.AccAddress) authtypes.AccountI
	SetAccount(ctx sdk.Context, acc authtypes.AccountI)
```

File: x/poolmanager/keeper/create_pool.go (hunk 1 above)
Comment (zale144) [reply x/poolmanager/keeper/create_pool.go:70]: @hoangdv2429 @mtsitrin this way no need for error check

Comment (mtsitrin) [reply x/poolmanager/keeper/create_pool.go:70]: not sure what the gain here.
I prefer the original way, as used in the vanilla SDK `GetModuleAccountAndPermissions`
we don't use it as it expects the module accounts to be registered in `app.go`.
as we create module accounts on the run, we just copy paste the relevant snippet

**Review by mtsitrin — APPROVED** [review]

File: x/poolmanager/keeper/create_pool.go (hunk 1 above)
Comment (zale144) [reply x/poolmanager/keeper/create_pool.go:70]: I see. Then best keep the code consistent. I just thought it would be a bit more concise and avoid err check, I didn't know how it was exactly done in SDK
