### PR TITLE
fix: after pools created failure to export and init genesis

### LINKED ISSUE #68: genesis validation of exported pool fails
Seems like even though the init succeeds the export fails. this is due to comsos check being done on module accont where name derives address (in the case of pools the name and address are the same)

### LINKED ISSUE #508: after pools created, failure to export and init genesis
After creating some pools (e.g using `scripts/pools/e2e.sh`)
and exporting the state,
we got some genesis file

if tested by `dymd validate-genesis` it returns the following errors:
```
invalid account found in genesis state; address: dym1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wsej4zfy, error: address dym1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wsej4zfy cannot be derived from the module name 'dym1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wsej4zfy'
``` 

and
```
name field cannot be blank
```

first one is due to accounts created for pools
the 2nd is due to bank denom data create for pools LP tokens

### PR DESCRIPTION
**Pull request by mtsitrin**
Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documation of area A by adding ....*

## Brief Changelog

*(for example:)*
 
  - *The metadata is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *Daemons retrieve the RPC data from the blob cache*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

File: x/poolmanager/keeper/create_pool.go [hunk 1]
```diff
@@ -61,11 +73,6 @@ func (k Keeper) CreatePool(ctx sdk.Context, msg types.CreatePoolMsg) (uint64, er
 		return 0, err
 	}
 
-	// create and save the pool's module account to the account keeper
-	if err := osmoutils.CreateModuleAccount(ctx, k.accountKeeper, pool.GetAddress()); err != nil {
```
Comment (mtsitrin) [inline x/poolmanager/keeper/create_pool.go:65]: @omritoptix this method was used to create module accounts. It set's name == address, which is wrong for Module accounts. (as module account have name-> Addr known transformation)

Comment (mtsitrin) [reply x/poolmanager/keeper/create_pool.go:65]: I set the Name and Addr to be `poolID->Name->Addr`
instead of 'poolID->Addr`
